### ISSUE TITLE
Add CSRF tokens for API actions

### ISSUE THREAD

**Issue by mattdowdell** [Altitude-Tech/sensly-api#19]
Pretty much all API actions should use CSRF token based authentication to improve security.

- [X] Implement CSRF token functionality (3fe888a).
- [ ] Implement token usage into each controller/action.
    - [X] V1::UsersController (a497430)
    - [X] V1::GroupsController (742e3cf)
    - [ ] V1::DevicesController
    - [ ] V1::Admin::DevicesController
- [ ] Document token usage on wiki
    - [X] [Users](/Altitude-Tech/sensly-api/wiki/Users)
    - [X] [Groups](/Altitude-Tech/sensly-api/wiki/Groups)
    - [ ] [Devices](/Altitude-Tech/sensly-api/wiki/Devices)
    - [ ] [Devices (Staff)](/Altitude-Tech/sensly-api/wiki/Devices-(Staff))
