### ISSUE TITLE
Implement admin users for admin only APIs

### ISSUE THREAD

**Issue by mattdowdell** [Altitude-Tech/sensly-api#20]
There is currently an admin-only API at `/v1/admin/devices` for creating new devices in the database. However, this is currently unrestricted.

- [X] Implement admin column in users table (55ce4b7).
- [ ] Implement a way to grant admin to users.
- [X] Add checks to admin controllers to require the user is an admin (55ce4b7).
- [X] Add tests (55ce4b7).

**Comment by mattdowdell** [comment]
Implemented in  55ce4b7
