### ISSUE TITLE
Improve logging for StandardError handling

### ISSUE THREAD

**Issue by mattdowdell** [Altitude-Tech/sensly-api#21]
The API currently handles StandardError (or children of) exceptions but only outputs an error message top the end user.

This should be improved by logging the error to the relevant log file (production/development/test) and sending an email to let maintainers know about the error in production.

## Tasks
- [X] - Log error to the relevant file.
- [X] - File should display level of error.
- [X] - File should display the time of the error in development and production.
- [ ] - Fatal errors caught by the API error handling should trigger a email message when in production to `errors@altitude.tech`.

**Comment by mattdowdell** [comment]
Additionally, the level and time should be added to the logs for easier detection when trying to grep/search for the error.
