### ISSUE TITLE
Implement sensor conversion library

### ISSUE THREAD

**Issue by mattdowdell** [Altitude-Tech/sensly-api#24]
Implement and test:
- [X] MQ2 Sensor (910f8a80f40d745b9b0c24fbd48eab54f6aabe56)
- [x] MQ7 Sensor (f74f4a5f9c03d637129b744a2826624afe2b1739)
- [x] MQ135 Sensor (714aeee140e383cb2e9b35928cff0641336cd0be)
- [x] PM Sensor (a1061dea91c09e39f01b6d71cb332e442b8504e8)

Minor block caused by #25

**Comment by mattdowdell** [comment]
Current status: Formulas appear to work, need to get correct 'band' limits for tests. Also need to check conversion of ADC to PPM based on CSV file (`~/Documents/Sensly_07-09-2016_09_28_42.csv`)
